version: '3.8'

services:
  backend:
    build: .
    container_name: 'insurance_backend'
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 1s
      retries: 3
    restart: always


volumes:
  postgres_data:
